### PR TITLE
Fix missing X-XHR-Redirected-To header following routes.rb redirect

### LINKED ISSUE #434: Redirecting root in routes.rb not reflected in address bar
If I have a route defined like:

```ruby
root to: redirect('/foo')
```

and a link created like:

```ruby
link_to('root', root_path)
```

then no `X-XHR-Redirected-To` header is sent and the URL in the address bar does not reflect the redirect.

### PR DESCRIPTION
**Pull request by Thibaut**
Fix #434

### CODE REVIEW

File: lib/turbolinks.rb [hunk 1]
```diff
@@ -27,6 +27,20 @@ def referer
           end
           alias referrer referer
         end
+
+        ActionDispatch::Routing::Redirect.class_eval do
+          def call_with_turbolinks(env)
+            status, headers, body = call_without_turbolinks(env)
+            session = ActionDispatch::Request::Session.find(env)
```
Comment (Thibaut) [inline lib/turbolinks.rb]: I don't like this, but Rails 4.0 doesn't let us access the request object it creates:
https://github.com/rails/rails/blob/4-0-stable/actionpack/lib/action_dispatch/routing/redirection.rb#L18
Unlike 4.2:
https://github.com/rails/rails/blob/4-2-stable/actionpack/lib/action_dispatch/routing/redirection.rb#L24

**Comment by Thibaut** [comment]
This doesn't work in Rails 3.2. I'll fix it later.

**Comment by Thibaut** [comment]
Updated
